Test4Theory Leaderboard for MCPLOTS stats

The following page and script uses the MCPLOTS data generated by the volunteers of 
the BOINC project Test4Theory.

The web pages shows the top users for the following categories:

  * Number of events
  * Number of jobs (total ammount, including good and bad ones)
  * Number of good jobs
  * Nominal CPU time (in seconds)

The charts are created using the library D3.JS and it will be only viewable in modern
web browsers like Firefox or Chrome.

License GPLv3 for the top5.js script.
